FROM apache/superset:latest

USER root

# Copy the requirements file into the container
COPY requirements.txt .

# Install drivers into the specific Superset venv path
# We use -r requirements.txt to keep the Dockerfile clean
RUN pip install --no-cache-dir -r requirements.txt --target /app/.venv/lib/python3.10/site-packages

USER superset