FROM python:3.10-slim

WORKDIR /app

# Set the Python Path so it can find the 'src' module
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn mlflow boto3 pandas

# Copy the source code
COPY ./src /app/src

# We use the module path. Since PYTHONPATH is /app, 
# it will look for /app/src/api/app.py
CMD ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]